.TH "BIGRAPHER-VALIDATE" 1 "" "BigraphER ${pkg_version}" "BigraphER Manual"

.SH NAME
bigrapher-validate \- Parse a model and check its validity

.SH SYNOPSIS
.P
.B bigrapher validate
[OPTIONS] <MODEL.big> [PRED.bilog]

.SH OPTIONS
.PP
.IP "-c <ASSIGNMENT ...>, --const <ASSIGNMENT ...>"
Specify a comma-separated list of variable assignments. Example: `x=4,t=.56'.
.IP "-d <DIR>, --export-decs <DIR>"
Export each declaration in the model (bigraphs and reaction rules) to a distinct file in
.IR DIR .
Dummy values are used to instantiate functional values.
.IP "-f <FORMAT>, --format <FORMAT>"
Specify a comma-separated list of output formats for options
.BR -d|--export-decs ,
.BR -t|--export-ts and
.BR -s|--export-states .
Supported formats are
.I svg
and
.IR dot .
This is equivalent to setting
.B $BIGFORMAT
to
.IR FORMAT .
.IP "-h, --help"
Display the list of options.
.IP "-q, --quiet"
Disable all output. This is equivalent to setting
.B $BIGQUIET
to a non-empty value.
.IP "-v, --verbose"
Be more verbose. This is equivalent to setting
.B $BIGVERBOSE
to a non-empty value.

.SH ENVIRONMENT
.PP
.IP BIGFORMAT
See option `-f|--format'.
.IP BIGQUIET
See option `-q|--quiet'.
.IP BIGVERBOSE
See option `-v|--verbose'.

.SH AUTHORS
.PP
Michele Sevegnani <Michele.Sevegnani@glasgow.ac.uk>

.SH FURTHER DOCUMENTATION
.PP
See <http://www.dcs.gla.ac.uk/~michele/bigrapher.html>.

.SH SEE ALSO
.PP
.BR bigrapher (1), 
.BR bigrapher-full (1),
.BR bigrapher-sim (1)
