.PHONY: build release install uninstall clean test doc

build:
	dune build @install

install:
	dune install

uninstall:
	dune uninstall

clean:
	dune clean

test:
	dune runtest

doc:
	dune build @doc
