image: ocaml/opam2:4.11

pipelines:
  default:
    - step:
        name: 'Build and Test'
        script:
          - echo "Your build and test goes here..."
          - sudo apt-get -qy update && sudo apt-get -qy upgrade && sudo apt-get -qy install m4 zlib1g-dev minisat graphviz
          - opam repo set-url --all-switches default https://opam.ocaml.org/ && opam update && opam install -y dune dune-configurator menhir cmdliner jsonm
          - eval $(opam env)
          - dune runtest -j 4
