image: ocaml/opam2:latest

definitions:
  caches:
    apt: /var/cache/apt/archives/
    opam: ~/.opam/download-cache/
  steps:
    - step: &build-test
        name: Build and test
        script:
          - sudo apt-get -qy update && sudo apt-get -qy upgrade && sudo apt-get -qy install m4 zlib1g-dev minisat graphviz
          - opam repo set-url --all-switches default https://opam.ocaml.org/ && opam update && opam install -y dune dune-configurator menhir cmdliner jsonm
          - eval $(opam env)
          - ocamlc --version
          - dune runtest -j 4

pipelines:
  default:
  - parallel:
    - step:
          <<: *build-test
          image: ocaml/opam2:4.08
          name: Build and test - 4.08
    - step:
          <<: *build-test
          name: Build and test - latest
    - step: *build-test
  - step:
        name: Static build
        script:
          - sudo apt-get -qy update && sudo apt-get -qy upgrade && sudo apt-get -qy install m4 zlib1g-dev minisat graphviz
          - opam repo set-url --all-switches default https://opam.ocaml.org/ && opam update && opam install -y dune dune-configurator menhir cmdliner jsonm
          - eval $(opam env)
          - dune build -j4 --profile=static bigrapher/src/bigrapher.exe
          - ldd _build/default/bigrapher/src/bigrapher.exe
          - dune build @doc
          - tar -czvf bigrapher.tar.gz _build/default/bigrapher/src/bigrapher.exe
          - tar -czvf doc.tar.gz _build/default/_doc/_html
        artifacts:
          - bigrapher.tar.gz
          - doc.tar.gz
