bin: [
  "?_build/bin/bigrapher.byte" {"bigrapher"}
  "?_build/bin/bigrapher.native" {"bigrapher"}
]

man: [
  "man/bigrapher.1" {"man1/bigrapher.1"}
  "man/bigrapher-validate.1" {"man1/bigrapher-validate.1"}
  "man/bigrapher-full.1" {"man1/bigrapher-full.1"}
  "man/bigrapher-sim.1" {"man1/bigrapher-sim.1"}
]

share_root: [
  "big-mode/big-mode.el" {"emacs/site-lisp/big-mode.el"}
  "?big-mode/big-mode.elc" {"emacs/site-lisp/big-mode.elc"}
]